#!/usr/bin/env bash
# Install nginx and start it

sudo apt-get update
sudo apt-get -y install nginx
# service nginx start
# ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx restart
