#!/usr/bin/env bash
# Install nginx and start it
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "school\n" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
